### ISSUE TITLE
Getting NullPointerException When Running When Trying To Read Stream

### ISSUE THREAD

**Issue by ghost** [maropu/spark-kinesis-sql-asl#1]
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 23.0 failed 4 times, most recent failure: Lost task 0.3 in stage 23.0 (TID 71, 10.0.145.199): java.lang.NullPointerException

at org.apache.spark.streaming.kinesis.KinesisSnapshotRDD$$anon$1.apply(KinesisSnapshotRDD.scala:93)
	at org.apache.spark.streaming.kinesis.KinesisSnapshotRDD$$anon$1.apply(KinesisSnapshotRDD.scala:90)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:393)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1917)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1917)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1891)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1904)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1917)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1324)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1298)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply$mcZ$sp(RDD.scala:1432)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1432)
	at org.apache.spark.rdd.RDD$$anonfun$isEmpty$1.apply(RDD.scala:1432)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.isEmpty(RDD.scala:1431)
	at org.apache.spark.sql.kinesis.KinesisSource$.inferSchema(KinesisSource.scala:550)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider$$anonfun$2.apply(KinesisSourceProvider.scala:43)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider$$anonfun$2.apply(KinesisSourceProvider.scala:43)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider.sourceSchema(KinesisSourceProvider.scala:42)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:220)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:80)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:80)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:30)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:124)
	at line890d2a64040f43e784200d50cb8d2a0241.$read$$iw$$iw$$iw$$iw.<init>(<console>:44)
	at line890d2a64040f43e784200d50cb8d2a0241.$read$$iw$$iw$$iw.<init>(<console>:51)
	at line890d2a64040f43e784200d50cb8d2a0241.$read$$iw$$iw.<init>(<console>:53)
	at line890d2a64040f43e784200d50cb8d2a0241.$read$$iw.<init>(<console>:55)
	at line890d2a64040f43e784200d50cb8d2a0241.$eval$.$print$lzycompute(<console>:7)
	at line890d2a64040f43e784200d50cb8d2a0241.$eval$.$print(<console>:6)
Caused by: java.lang.NullPointerException
	at org.apache.spark.streaming.kinesis.KinesisSnapshotRDD$$anon$1.apply(KinesisSnapshotRDD.scala:93)
	at org.apache.spark.streaming.kinesis.KinesisSnapshotRDD$$anon$1.apply(KinesisSnapshotRDD.scala:90)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:393)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:59)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:104)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:48)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:310)
	at scala.collection.AbstractIterator.to(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:302)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:289)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1336)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.rdd.RDD$$anonfun$take$1$$anonfun$29.apply(RDD.scala:1324)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1917)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:1917)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by maropu** [comment]
Could you share simple queries to reproduce this exception?
