### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.kinesis.KinesisSource$

### ISSUE THREAD

**Issue by DimaTolkachIt** [maropu/spark-kinesis-sql-asl#3]
Hi,

I added the .jar as a library to my cluster, but I can't start loading data in Notebook.

```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.spark.sql.kinesis.KinesisSource$
	at org.apache.spark.sql.kinesis.KinesisSourceProvider$$anonfun$2.apply(KinesisSourceProvider.scala:43)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider$$anonfun$2.apply(KinesisSourceProvider.scala:43)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.kinesis.KinesisSourceProvider.sourceSchema(KinesisSourceProvider.scala:42)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceSchema(DataSource.scala:199)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo$lzycompute(DataSource.scala:87)
	at org.apache.spark.sql.execution.datasources.DataSource.sourceInfo(DataSource.scala:87)
	at org.apache.spark.sql.execution.streaming.StreamingRelation$.apply(StreamingRelation.scala:30)
	at org.apache.spark.sql.streaming.DataStreamReader.load(DataStreamReader.scala:125)
```

**Comment by maropu** [comment]
Thanks for the report! Since I worked in the master branch directly, it seems the branch got broken. I've fixed this issue, so I'm happy you try this and report more :) Thanks!
